### PR TITLE
23 add pre commit in plurality dashboard UI to make sure commit message patterns match the semantic release pattern

### PR DESCRIPTION
**Pull request by zhutianlei24**

### CODE REVIEW

**Comment by zhutianlei24** [comment]
Know How:

Install Husky -> 
`$ npm i -D husky`
`$ npx husky install`
`$ npm set-script prepare "husky install"`

Install Commitlint with conventional commits-> 
`$ npm i -D @commitlint/config-conventional @commitlint/cli`
Create a `commitlint.config.js` in the root folder and add `module.exports = {extends: ['@commitlint/config-conventional']}` in it
Add the husky hook
`npx husky add .husky/commit-msg  'npx --no -- commitlint --edit ${1}'`

**Review by mujtabaidrees94 — COMMENTED** [review]
Where have we added the commit pattern regx and how to test it? 

I can still commit without following the required pattern in this branch and there is no local or remote commit message verification in this case.

**Review by mujtabaidrees94 — APPROVED** [review]

**Comment by mujtabaidrees94** [comment]
Added semantic PR app that forces us to have correct message format

**Pull request merged**
